server:
  port: 8084
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/json
  tomcat:
    max-connections: 30000
  servlet:
    context-path: /admin
    uri-encoding: UTF-8


logging:
  config: classpath:logback-spring.xml

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      maxFileSize: "1000MB"
      maxRequestSize: "10000MB"
  application:
    name: admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  freemarker:
    settings:
      classic_compatible: true #空值处理
    checkTemplateLocation: false
  log:
    application: admin
    base: /home/admin/log
    atcionPrefix: v3


  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat,wall,slf4j
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://119.45.57.249:3306/test?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: true
        login-username: druid
        login-password: test123qaz
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: com.zy.intelligentdevice.db.mapper.*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.zy.intelligentdevice.db.model  # 注意：对应实体类的路径

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

